version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/aws/aws-sdk-go
    versions:
    - 1.38.22
    - 1.38.23
    - 1.38.24
    - 1.38.25
    - 1.38.26
    - 1.38.27
