#!/bin/bash

set -e -u

export GOPATH=$PWD/gopath
export PATH=$PWD/gopath/bin:$PATH

assets=$PWD/assets

version="0.0.0-dev"
if [ -d version ]; then
  version="$(cat version/version)"
fi
echo "Building version $version"

echo "Building binaries"
pushd get-aws-session-token
  go mod init get-aws-session-token
  go mod tidy
  for os in linux darwin windows; do
    ext=""
    if [ "$os" = "windows" ]; then
      ext=".exe"
    fi
    echo "building $os binary..."
    GOOS=$os go build \
      -o $assets/get-aws-session-token-${os}_amd64${ext} \
      github.com/uid0/get-aws-session-token
  done
popd

echo "Version built: $version"