resource_types:
- name: pull-request
  type: registry-image
  source:
    repository: jtarchie/pr

- name: github-status
  type: registry-image
  source:
    repository: resource/github-status


resources:
- name: get-aws-session-token
  type: git
  source: 
    uri: "https://github.com/uid0/get-aws-session-token.git"
    branch: master

- name: version
  type: semver
  source:
    driver: git
    initial_version: 0.0.0
    uri: git@github.com:uid0/get-aws-session-token
    branch: version
    file: version
    private_key: ((repo_private_key))

- name: release-notes
  type: git
  source:
    uri: https://github.com/uid0/get-aws-session-token/
    branch: version

- name: gh-status
  type: github-status
  source:
    repo: vito/booklit
    access_token: ((prs_access_token))


jobs:
- name: unit
  plan:
  - get: getsession
    trigger: true
  - task: test
    file: get-aws-session-token/ci/test.yml
  - task: build
    file: get-aws-session-token/ci/build.yml

- name: major
  public: true
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: major, pre: rc}
  - put: version
    params: {file: version/version}

- name: minor
  public: true
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: minor, pre: rc}
  - put: version
    params: {file: version/version}

- name: patch
  public: true
  serial_groups: [version]
  plan:
  - get: version
    passed: [ship]
    params: {bump: patch, pre: rc}
    trigger: true
  - put: version
    params: {file: version/version}

- name: ship
  public: true
  serial_groups: [version]
  plan:
  - get: getsession
    passed: [rc]
  - get: final-version
    resource: version
    passed: [rc]
    params: {bump: final}
  - get: release-notes
  - task: build
    file: booklit/ci/build.yml
    input_mapping: {version: final-version}
  - task: grab-release-notes
    file: booklit/ci/grab-release-notes.yml
  - put: version
    params: {file: final-version/version}
  - put: booklit-rel
    params:
      tag: version/version
      tag_prefix: v
      committish: booklit/.git/HEAD
      name: release-info/name
      body: release-info/notes.md
      globs: [assets/*]
